### PR TITLE
resolve deprecation

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolve deprecation cop warning:
:warning: Store package settings file in the `settings/` directory instead of `scoped-properties/`
and set the min and max api version

### CODE REVIEW

**Comment by fabean** [comment]
Been over a month, this is still an issue that needs to be merged into master.

At this point do we just fork it and abandon this version?

@ChristianMurphy

**Comment by ChristianMurphy** [comment]
@fabean 
Probably,
I've moved to using https://atom.io/packages/language-jade
But we could also fork this repo and update.

**Comment by merrihew** [comment]
Hey folks, apologies for letting this API deprecation languish... I've closed it with #26, deprecation warning should disappear.  If anyone would like to help maintain the project, specifically getting some of the grammars updated, get in touch as I'd appreciate the help!

**Comment by ChristianMurphy** [comment]
@merrihew I would be interested in helping to update the grammar some to better integrate with atom 1.0 auto complete
https://github.com/atom/autocomplete-plus/wiki/SymbolProvider-Config-API

**Comment by merrihew** [comment]
@ChristianMurphy I'm not well-versed with the `autocomplete-plus`, but totally open to making this package work better with other plugins. Want to take a first take at those changes and open up a PR? If everything looks good I'll add you to the repo!

**Pull request closed without merging**
