### PR TITLE
Symbol Provider

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Features**
- Sets Minimum and Maximum Atom API level
- Adds Autocompletion for basic Jade builtins

e.g.
example

[original conversation](https://github.com/merrihew/atom-jade/pull/4#issuecomment-105564037)

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@merrihew here is a simple autocomplete for the basic Jade builtins.

One note on running this, it requires `atom 0.199.0` or higher for autocomplete to show up correctly.

**Comment by ChristianMurphy** [comment]
added completion for for `id`, `class`, `attribute` and `tag`.
these completions are based off of existing content in the file.
unlike the jade completions which are based off predefined snippets.
example
example

**Comment by ChristianMurphy** [comment]
One thing which I did notice while working on this.

These get labeled as `tag`

``` jade
block
extends
case
when
default
if
else if
else
each
while
```

These are not labeled as `tag`

``` jade
mixin
include
```

having Jade buitins labeled as tag isn't a problem necessarily, it just means functions will sometimes show an additional completion as a `tag`.
example

I'll take a look into capturing these separate from tags later this afternoon/evening.

**Comment by ChristianMurphy** [comment]
added support for keywords, duplication no longer shows in autocomplete

example

**Comment by ChristianMurphy** [comment]
added value completion

example

**Comment by ChristianMurphy** [comment]
added mixin parameter and block name completion

example

**Comment by ChristianMurphy** [comment]
@merrihew 
I think this is ready for a test drive :car: 
and code review :eyes:

**Comment by merrihew** [comment]
Thanks @ChristianMurphy, I appreciate all the work so far! I'll take a look today.

**Comment by ChristianMurphy** [comment]
Ping @merrihew any thoughts on this?

**Pull request closed without merging**
